rage/concepts

- backend/datamodel.prisma
- backend/generated/prisma-client/index.d.ts
- backend/generated/prisma-client/index.js
- backend/generated/prisma-client/prisma-schema.js
- backend/index.js
- backend/schema.graphql
- frontend/package-lock.json
- frontend/src/App.js
- frontend/src/components/Concept.js
- frontend/src/components/ConceptForm.js
- frontend/src/components/ConceptList.js
- frontend/src/components/Users.js
- Create concept, resolves: #19 
- Delete concept, resolves: #8 #9 
- List concepts, resolves: #18
> Concept crud

- backend/datamodel.prisma
- backend/generated/prisma-client/index.d.ts
- backend/generated/prisma-client/index.js
- backend/generated/prisma-client/prisma-schema.js
- backend/index.js
- backend/schema.graphql
- frontend/src/App.js
- frontend/src/components/Course.js
- frontend/src/components/CourseForm.js
- frontend/src/components/CourseList.js
- frontend/src/services/ConceptService.js
- frontend/src/services/CourseService.js
- Create course: resolves: #4 resolves: #2 
- Added mutations and queries to backend:
* allCourses - query
* createCourse - mutation
* deleteCourse - mutation 
* updateConcept - mutation 
* changes to createConceptAndLinkTo and to createConcept
> Course creation

- backend/generated/prisma-client/index.d.ts
- backend/index.js
- backend/schema.graphql
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.js
- frontend/src/components/Concept.js
- frontend/src/components/ConceptForm.js
- frontend/src/components/ConceptList.js
- frontend/src/components/Course.js
- frontend/src/components/CourseList.js
- frontend/src/index.js
- frontend/src/services/ConceptService.js
- frontend/src/services/CourseService.js
- Add concepts specifically for that course
- Add prerequisite concepts to concepts of a course
- Url routing for "views", resolves #3
> Page for a single course and in its concepts

- backend/datamodel.prisma
- backend/generated/prisma-client/index.d.ts
- backend/generated/prisma-client/index.js
- backend/generated/prisma-client/prisma-schema.js
- backend/index.js
- backend/schema.graphql
- Create resources, resolves: #25
- Create urls to resources
> Concept resources in API

- backend/datamodel.prisma
- backend/generated/prisma-client/index.d.ts
- backend/generated/prisma-client/prisma-schema.js
- backend/index.js
- backend/schema.graphql
- frontend/src/App.css
- frontend/src/App.js
- frontend/src/components/Concept.js
- frontend/src/components/ConceptList.js
- frontend/src/components/CourseForm.js
- frontend/src/components/CourseList.js
- frontend/src/components/Resource.js
- frontend/src/components/ResourceForm.js
- frontend/src/services/CourseService.js
- frontend/src/services/ResourceService.js
- Create resources for concept, resolves #28 
- Show resources for a prerequisite
> Show resources with concepts

- frontend/src/components/concept/ConceptButton.js
- frontend/src/components/concept/ConceptUpdateForm.js
- frontend/src/components/course/CourseView.js
- Update concept by double clicking a concept, resolves: #13 
- Swapped locations between course tray and active course
> Concept update

- backend/.env.dev
- backend/.env.prod
- backend/generated/prisma-client/index.d.ts
- backend/generated/prisma-client/index.js
- backend/index.js
- backend/package.json
- backend/prisma.yml
- backend/yarn.lock
- Add scripts for starting the project locally and production
> Dotenv config

- backend/index.js
- backend/package.json
- backend/schema.graphql
- frontend/package.json
- frontend/src/AltApp.js
- frontend/src/App.css
- frontend/src/components/common/NavBar.js
- frontend/src/components/concept/ConceptButton.js
- frontend/src/components/concept/MaterialActiveConcept.js
- frontend/src/components/concept/MaterialConcept.js
- frontend/src/components/course/AltCourseList.js
- frontend/src/components/course/CourseContainer.js
- frontend/src/components/course/CourseView.js
- frontend/src/components/course/MaterialActiveCourse.js
- frontend/src/components/course/MaterialCourse.js
- frontend/src/components/course/MaterialCourseList.js
- frontend/src/components/course/MaterialCourseTray.js
- frontend/src/index.css
- frontend/src/index.js
- frontend/src/services/CourseService.js
- frontend/yarn.lock
- yarn.lock
- Delete course, resolves: #23 
- Can modify course, resolves: #5 
- UI redesign, resolves: #39 
- titles
- navigation
- material-ui styles
- better shows actions available to the users
- added more dialogs
> Material ui

- frontend/package.json
- frontend/src/App.js
- frontend/src/components/concept/MaterialConcept.js
- frontend/src/components/course/CourseContainer.js
- frontend/src/components/course/CourseMatrice.js
- frontend/src/components/course/CourseView.js
- frontend/src/components/course/MaterialActiveCourse.js
- frontend/src/components/course/MaterialCourse.js
- frontend/src/components/course/MaterialCourseList.js
- frontend/src/components/course/MaterialCourseTray.js
- frontend/src/components/course/MatriceView.js
- frontend/src/index.js
- frontend/src/services/ConceptService.js
- frontend/yarn.lock
* Add matrix view, resolves: #41 
* Add concept linking to matrix view, resolves: #42 
* Add filter to matrix view, resolves: #43 
* Add optimistic responses for mutations in course matrix
> Course matrix

- frontend/src/App.js
- frontend/src/components/concept/ActiveConcept.js
- frontend/src/components/course/CourseContainer.js
- frontend/src/components/course/CourseMatrix.js
- frontend/src/components/course/GuidedCourseContainer.js
- frontend/src/components/course/GuidedCourseTray.js
- frontend/src/components/course/GuidedCourseView.js
- Recolour and rename matrix buttons, resolves: #62, resolves: #61 
- Create guiding components, resolves: #63
- Add snackbars to inform user which action to take 
- Dynamic layout to guide interaction
> Guided course view

- frontend/src/components/concept/ActiveConcept.js
- frontend/src/components/concept/Concept.js
- frontend/src/components/course/Course.js
- frontend/src/components/course/CourseView.js
- frontend/src/components/course/GuidedCourseContainer.js
- frontend/src/components/course/GuidedCourseTray.js
- frontend/src/components/course/GuidedCourseView.js
- Change highlight to switch for indicating linkage between concepts
- Fixed toggle for hiding courseTray
- Navigation between courses using card headers
> Linking interaction

- backend/.env.dev
- backend/.env.prod
- backend/.gitignore
- backend/TMCAuthentication.js
- backend/accessControl.js
- backend/datamodel.prisma
- backend/generated/prisma-client/index.d.ts
- backend/generated/prisma-client/index.js
- backend/generated/prisma-client/prisma-schema.js
- backend/index.js
- backend/middleware/authentication.js
- backend/package.json
- backend/schema.graphql
- backend/yarn.lock
- frontend/package.json
- frontend/src/App.js
- frontend/src/apolloClient.js
- frontend/src/components/authentication/AuthenticationForm.js
- frontend/src/components/common/NavBar.js
- frontend/src/components/course/Course.js
- frontend/src/components/course/CourseList.js
- frontend/src/components/course/GuidedCourseContainer.js
- frontend/src/components/course/MatrixView.js
- frontend/src/index.js
- frontend/src/lib/authentication.js
- frontend/src/store.js
- frontend/yarn.lock
- Can authenticate using TMC, resolves: #12 
- Added authentication form 
- Added accounts to backend
- Added authentication middleware to protect resolvers
> TMC authentication

- backend/index.js
- frontend/src/App.js
- frontend/src/components/common/PrivateRoute.js
- frontend/src/components/concept/ActiveConcept.js
- frontend/src/components/concept/Concept.js
- frontend/src/components/concept/ConceptAdditionDialog.js
- frontend/src/components/concept/ConceptEditingDialog.js
- frontend/src/components/course/ActiveCourse.js
- frontend/src/components/course/Course.js
- frontend/src/components/course/CourseCreationDialog.js
- frontend/src/components/course/CourseEditingDialog.js
- frontend/src/components/course/CourseList.js
- frontend/src/components/course/GuidedCourseContainer.js
- frontend/src/components/course/GuidedCourseTray.js
- frontend/src/components/course/GuidedCourseView.js
- frontend/src/index.js
- frontend/src/store.js
Add authorisation to resources, resolves: #67 
- Disable buttons when not logged in
- Add error messages when error occurs, resolves: #72 
- Add authorisation to backend (access control to backend resolvers)
> Resource authorisation

- frontend/src/App.js
- frontend/src/components/course/CourseHeatmap.js
- frontend/src/components/course/heatmap.css
- frontend/src/components/workspace/WorkspaceList.js
- frontend/src/graphql/Query/Workspace.js
Add course heatmap, resolves: #79
* Added button to workspaces
* Created heatmap endpoint
* Hovering on heatmap cells shows concepts that are prerequisites
> Add courseheatmap

- frontend/src/components/course/CourseHeatmap.js
Add circular progress to course heatmap when loading data.
> Add circular progress to heatmap

- backend/middleware/authentication.js
- backend/resolvers/Mutation/ConceptLink.js
- backend/resolvers/Mutation/CourseLink.js
- Only one link can be created between two courses or two concepts per direction.
> One link per direction for courses and concepts

- frontend/src/components/concept/ActiveConcept.js
- frontend/src/components/concept/Concept.js
- frontend/src/components/course/ActiveCourse.js
- frontend/src/components/course/GuidedCourseTray.js
> Add proper word wrap for names

- frontend/src/components/authentication/AuthenticationForm.js
- frontend/src/components/porting/PortView.js
> Add loading indicator for login

- backend/resolvers/Query/Port.js
> Add linking to data export

- frontend/src/components/concept/ConceptAdditionDialog.js
- frontend/src/components/concept/ConceptEditingDialog.js
- frontend/src/components/course/ActiveCourse.js
- frontend/src/components/course/CourseCreationDialog.js
- frontend/src/components/course/CourseEditingDialog.js
- frontend/src/components/course/GuidedCourseContainer.js
- frontend/src/components/porting/PortView.js
- frontend/src/components/project/ProjectCreationDialog.js
- frontend/src/components/project/ProjectEditingDialog.js
- frontend/src/components/workspace/WorkspaceCreationDialog.js
- frontend/src/components/workspace/WorkspaceEditingDialog.js
> Prevent accidental submit on double click

- frontend/src/components/course/ActiveCourse.js
- frontend/src/components/course/GuidedCourseView.js
- Edit button to change name of "activeCourse"
- Also fix responsiveness of columns
> Add edit button to activeCourse

- backend/errorLogger.js
- backend/index.js
- backend/resolvers/Mutation/Port.js
fixes: #90 
Add error logging to server to show in which mutation or query the error has occurred in.
> Server error logging

- frontend/src/components/course/CourseMatrix.js
Update mouse events to use css attributes instead of react hooks.
> Improve matrix view performance

- frontend/src/App.js
- frontend/src/components/common/NavBar.js
- frontend/src/components/common/WorkspaceNavBar.js
- frontend/src/components/concept/ConceptLink.js
- frontend/src/components/workspace/WorkspaceList.js
> Add workspace bottom navbar

- frontend/src/components/course/ActiveCourse.js
- frontend/src/components/course/GuidedCourseView.js
Fixes #145
This pull request uses the last option commented on the issue.
> Add course navigation

- backend/datamodel.prisma
- backend/generated/prisma-client/index.d.ts
- backend/generated/prisma-client/prisma-schema.js
- backend/generated/schema.graphql
- backend/resolvers/Mutation/Port.js
- backend/resolvers/Mutation/Workspace.js
- backend/resolvers/Mutation/port.schema.json
- backend/resolvers/Query/Port.js
- backend/resolvers/Type/Workspace.js
- backend/schema-extra.graphql
- frontend/src/components/porting/PortView.js
- frontend/src/components/workspace/WorkspaceDefaultCourseForm.js
- frontend/src/components/workspace/WorkspaceView.js
- frontend/src/graphql/Mutation/Workspace.js
- frontend/src/graphql/Query/Course.js
- frontend/src/graphql/Query/Workspace.js
> Default course removal

- backend/datamodel.prisma
- backend/generated/prisma-client/index.d.ts
- backend/generated/prisma-client/prisma-schema.js
- backend/generated/schema.graphql
- backend/middleware/authentication.js
In order to keep track of inactive users
> Keep track of guests

- backend/resolvers/Mutation/Authentication.js
Give TMC-admins admin privileges.
> TMC-admin privileges

- frontend/src/components/course/CourseHeatmap.js
Add message to courseheatmap when there's no data available to make heatmap from.
> Course Heatmap when there's no data

- frontend/src/components/concept/ConceptAdditionDialog.js
- frontend/src/components/concept/ConceptEditingDialog.js
- frontend/src/components/course/CourseCreationDialog.js
- frontend/src/components/course/CourseEditingDialog.js
- frontend/src/components/project/CloneView.js
- frontend/src/components/project/ProjectCreationDialog.js
- frontend/src/components/project/ProjectEditingDialog.js
- frontend/src/components/project/TemplateCreationDialog.js
- frontend/src/components/workspace/WorkspaceCreationDialog.js
- frontend/src/components/workspace/WorkspaceDefaultCourseForm.js
- frontend/src/components/workspace/WorkspaceEditingDialog.js
Trim whitespaces in dialogs. fixes: #171
> Trim whitespaces

- frontend/src/App.js
- frontend/src/components/common/AuthIcon.js
- frontend/src/components/common/NavBar.js
- frontend/src/components/common/WorkspaceNavBar.js
- frontend/src/components/course/ActiveCourse.js
- frontend/src/components/course/Course.js
- frontend/src/components/course/CourseHeatmap.js
- frontend/src/components/course/GuidedCourseContainer.js
- frontend/src/components/course/GuidedCourseView.js
- frontend/src/components/project/CloneView.js
- frontend/src/components/project/ProjectView.js
- frontend/src/components/project/TemplateList.js
- frontend/src/components/project/UserWorkspaceList.js
- frontend/src/components/workspace/WorkspaceDefaultCourseForm.js
- frontend/src/components/workspace/WorkspaceView.js
> Navigation breadcrumbs

- frontend/src/apollo/apolloClient.js
- frontend/src/components/common/NavBar.js
> Add global saving indicator

- backend/src/resolvers/Mutation/Port.js
- backend/src/resolvers/Mutation/port.schema.json
- frontend/src/components/porting/PortView.js
- frontend/src/graphql/Query/Project.js
- frontend/src/graphql/Query/Workspace.js
Add select option in porting view.
> Select workspace on import

- backend/src/resolvers/Mutation/Course.js
- frontend/src/components/course/GuidedCourseTray.js
- frontend/src/components/porting/PortView.js
Add delete and edit options to courses in course tray. fixes: #180
> Course editing in course tray

- frontend/src/views/mapper/CourseTray.js
Allow removal of the last course or the course that is currently being edited.
> Active course removal

- frontend/src/views/mapper/concept/ActiveConcept.js
- frontend/src/views/mapper/concept/Concept.js
Add tooltip to concepts on hover
> Concept description tooltip on hover

- frontend/package.json
- frontend/src/index.js
- frontend/src/views/graph/GraphView.js
- frontend/yarn.lock
Change visjs to vis-network 5.2.1
> Change visjs to vis-network

- frontend/src/views/heatmap/HeatmapView.js
Flip heatmap the other way around.
> Switch heatmap's target and prerequisite

- frontend/src/views/graph/CytoGraphView.js
> Add sane zoom limits

- frontend/src/views/graph/CytoGraphView.js
> Add reset layout button to graph view

- frontend/src/views/graph/CytoGraphView.js
> Add zoom slider to graph view

- frontend/package.json
- frontend/src/views/graph/CytoGraphView.js
- frontend/yarn.lock
> Cytoscape popper

- frontend/src/views/graph/CytoGraphView.js
> Concept graph legend

- frontend/src/views/graph/CytoGraphView.js
> Highlight path to predecessors and successors

- frontend/src/App.js
- frontend/src/components/NavBar.js
- frontend/src/views/mapper/CourseMapperView.js
- frontend/src/views/mapper/CourseTray.js
- frontend/src/views/project/TemplateList.js
> Improve navigation breadcrumbs

- frontend/src/components/NavBar.js
- frontend/src/views/mapper/ActiveCourse.js
- frontend/src/views/mapper/CourseContainer.js
- frontend/src/views/mapper/CourseMapperView.js
- frontend/src/views/mapper/CourseTray.js
- frontend/src/views/mapper/DividerWithText.js
- frontend/src/views/mapper/Masonry.js
- frontend/src/views/mapper/concept/Concept.js
> Swap course tray and active course

- frontend/src/views/porting/PortView.js
- Set fewer rows to make it fit to shorter screens
- Add text to template
> Improve portview

- frontend/src/components/LoadingBar.js
- frontend/src/components/NavBar.js
- frontend/src/dialogs/concept/useCreateConceptDialog.js
- frontend/src/index.js
- frontend/src/views/graph/CytoGraphView.js
- frontend/src/views/heatmap/HeatmapView.js
- frontend/src/views/home/UserViewContent.js
- frontend/src/views/login/LoginView.js
- frontend/src/views/mapper/CourseMapperView.js
- frontend/src/views/project/CloneView.js
- frontend/src/views/project/ProjectView.js
- frontend/src/views/workspace/WorkspaceManagementView.js
> Use new global loading bar

- frontend/src/components/BaseWorkspaceList.js
- frontend/src/components/NavBar.js
- frontend/src/components/WorkspaceNavBar.js
- frontend/src/dialogs/Dialog.js
- frontend/src/views/graph/CytoGraphView.js
- frontend/src/views/home/HomeView.js
- frontend/src/views/home/UserViewContent.js
- frontend/src/views/project/MergeList.js
- frontend/src/views/project/UserWorkspaceList.js
- Set lines on bottom of navigation bars
> Add minor improvements to UI

- frontend/src/components/LoadingBar.js
- frontend/src/views/graph/CytoGraphView.js
- frontend/src/views/mapper/CourseMapperView.js
- frontend/src/views/mapper/concept/ConceptLink.js
https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html
> Update lifecycle method names

- backend/src/resolvers/Mutation/Port.js
- backend/src/resolvers/Query/Port.js
- backend/src/static/port.schema.json
- frontend/src/graphql/Mutation/Port.js
- frontend/src/views/porting/PortView.js
> Update porting to include official field

- frontend/src/dialogs/Dialog.js
- frontend/src/dialogs/concept/useCreateConceptDialog.js
- frontend/src/dialogs/concept/useEditConceptDialog.js
- frontend/src/dialogs/course/useCreateCourseDialog.js
- frontend/src/dialogs/course/useEditCourseDialog.js
- frontend/src/graphql/Mutation/Course.js
- frontend/src/graphql/Mutation/CourseLink.js
- frontend/src/graphql/Query/Course.js
- frontend/src/graphql/Query/Workspace.js
- frontend/src/views/manager/CourseEditor.js
- frontend/src/views/manager/CourseList.js
- frontend/src/views/manager/WorkspaceManagementView.js
- frontend/src/views/mapper/ActiveCourse.js
- frontend/src/views/mapper/Course.js
- frontend/src/views/mapper/CourseTray.js
- frontend/src/views/mapper/concept/Concept.js
> Set or edit official status for courses and concepts

- backend/schema/extra.graphql
- backend/schema/generated/schema.graphql
- backend/src/errors.js
- backend/src/resolvers/Mutation/Merge.js
- frontend/package.json
- frontend/src/dialogs/Dialog.js
- frontend/src/dialogs/sharing/LinkSharingActions.js
- frontend/src/graphql/Mutation/Concept.js
- frontend/src/graphql/Mutation/Merge.js
- frontend/src/views/manager/CourseEditor.js
- frontend/src/views/manager/MergeDialog.js
- frontend/src/views/manager/WorkspaceManagementView.js
- frontend/yarn.lock
> Add concept merging

- backend/yarn.lock
- frontend/package.json
- frontend/src/dialogs/Dialog.js
- frontend/src/dialogs/concept/TaxonomyTags.js
- frontend/src/dialogs/concept/tagSelectUtils.js
- frontend/src/dialogs/concept/useCreateConceptDialog.js
- frontend/src/dialogs/concept/useEditConceptDialog.js
- frontend/src/views/manager/CourseEditor.js
- frontend/src/views/manager/MergeDialog.js
- frontend/yarn.lock
> Use react-select for tags in concept editors

- frontend/src/views/manager/CourseEditor.js
> Filter concepts in manager

- backend/src/resolvers/Mutation/Authentication.js
> Switch to production access control

- frontend/src/graphql/Query/Sharing.js
- frontend/src/views/join/JoinView.js
- frontend/src/views/project/CloneView.js
> Simplify project clone flow

- frontend/src/dialogs/Dialog.js
- frontend/src/views/join/JoinView.js
- frontend/src/views/manager/CourseEditor.js
- frontend/src/views/manager/CourseList.js
> Move official checkbox next to buttons

- frontend/src/views/mapper/ActiveCourse.js
- frontend/src/views/mapper/CourseMapperView.js
- frontend/src/views/mapper/CourseTray.js
- frontend/src/views/mapper/PrerequisiteContainer.js
> Swap linking direction in guide

- frontend/src/views/manager/CourseEditor.js
> Sorting concepts

- frontend/src/components/AuthIcon.js
- frontend/src/lib/authentication.js
> Indicate what account the user is logged into

- backend/docker-compose.yml
- frontend/src/components/AuthIcon.js
- frontend/src/components/BaseWorkspaceList.js
- frontend/src/views/heatmap/HeatmapView.js
- frontend/src/views/home/HomeView.js
- frontend/src/views/home/UserViewContent.js
- frontend/src/views/mapper/ActiveCourse.js
* Add tooltip to active course
> Minor tweaks to UI

- frontend/src/dialogs/Dialog.js
- frontend/src/dialogs/concept/useCreateConceptDialog.js
- frontend/src/dialogs/concept/useEditConceptDialog.js
- frontend/src/dialogs/course/useCreateCourseDialog.js
- frontend/src/dialogs/course/useEditCourseDialog.js
- frontend/src/dialogs/tagSelectUtils.js
- frontend/src/views/manager/CourseEditor.js
- frontend/src/views/manager/CourseList.js
- frontend/src/views/manager/MergeDialog.js
- frontend/src/views/mapper/ActiveCourse.js
- frontend/src/views/mapper/CourseTray.js
Add course related tags to mapper view.
> Course themes

- backend/schema/extra.graphql
- backend/schema/generated/schema.graphql
- backend/src/resolvers/Mutation/Concept.js
- backend/src/resolvers/Mutation/Course.js
- backend/src/resolvers/Mutation/CourseLink.js
- backend/src/resolvers/Mutation/Workspace.js
- frontend/src/apollo/update/courseLink.js
- frontend/src/components/ProjectNavBar.js
- frontend/src/components/WorkspaceNavBar.js
- frontend/src/dialogs/Dialog.js
- frontend/src/dialogs/concept/useCreateConceptDialog.js
- frontend/src/dialogs/concept/useEditConceptDialog.js
- frontend/src/dialogs/course/useCreateCourseDialog.js
- frontend/src/dialogs/course/useEditCourseDialog.js
- frontend/src/graphql/Mutation/Concept.js
- frontend/src/graphql/Mutation/Course.js
- frontend/src/graphql/Mutation/CourseLink.js
- frontend/src/graphql/Mutation/Merge.js
- frontend/src/graphql/Query/Course.js
- frontend/src/graphql/Query/Workspace.js
- frontend/src/views/manager/CourseEditor.js
- frontend/src/views/manager/CourseList.js
- frontend/src/views/mapper/ActiveCourse.js
- frontend/src/views/mapper/Course.js
- frontend/src/views/mapper/CourseMapperView.js
- frontend/src/views/mapper/CourseTray.js
- frontend/src/views/mapper/PrerequisiteContainer.js
- frontend/src/views/mapper/concept/Concept.js
> Add freezing to UI

- frontend/src/views/mapper/CourseMapperView.js
- frontend/src/views/mapper/CourseTray.js
- frontend/src/views/mapper/concept/Concept.js
- frontend/src/views/project/ProjectView.js
> Use JSS reference syntax

- frontend/src/graphql/Query/Course.js
- frontend/src/views/mapper/CourseMapperView.js
- frontend/src/views/mapper/CourseTray.js
- frontend/src/views/mapper/concept/ConceptLink.js
Something broke back when concept links were partly turned into functional components.
> Fix updating concept link target element after changing course links

- .dockerignore
- Dockerfile
- backend/docker-compose.yml
- backend/src/index.js
- docker-compose.yml
> Add docker stuff for production deployment

- backend/.dockerignore
- backend/schema/datamodel.prisma
- backend/schema/generated/prisma-client/index.d.ts
- backend/schema/generated/prisma-client/prisma-schema.js
- backend/schema/generated/schema.graphql
- backend/src/resolvers/Mutation/Concept.js
- backend/src/resolvers/Mutation/Merge.js
- backend/src/resolvers/Mutation/Port.js
- backend/src/resolvers/Mutation/Workspace.js
- backend/src/resolvers/Type/Concept.js
- frontend/.dockerignore
- frontend/src/apollo/update/concept.js
- frontend/src/components/FocusOverlay.js
- frontend/src/components/LoadingBar.js
- frontend/src/dialogs/DialogProvider.js
- frontend/src/dialogs/sharing/useShareDialog.js
- frontend/src/graphql/Mutation/Concept.js
- frontend/src/graphql/Mutation/Course.js
- frontend/src/graphql/Mutation/CourseLink.js
- frontend/src/graphql/Mutation/Merge.js
- frontend/src/graphql/Query/Course.js
- frontend/src/graphql/Query/Workspace.js
- frontend/src/views/graph/CytoGraphView.js
- frontend/src/views/heatmap/HeatmapView.js
- frontend/src/views/mapper/ActiveCourse.js
- frontend/src/views/mapper/CourseMapperView.js
- frontend/src/views/mapper/CourseTray.js
- frontend/src/views/mapper/PrerequisiteContainer.js
- frontend/src/views/mapper/concept/ConceptLink.js
Fixes #314 
~~Based on #315 (merge that first and then change the base of this pull request to `master`
done)~~ done
> Remove courses

- frontend/src/components/AuthIcon.js
> Add role to auth menu

- frontend/package.json
- frontend/src/views/manager/ConceptGroup.js
- frontend/src/views/manager/CourseEditor.js
- frontend/yarn.lock
> Add concept grouping

- frontend/src/components/BaseWorkspaceList.js
- frontend/src/static/userGuide.json
- frontend/src/views/home/ProjectList.js
- frontend/src/views/home/UserViewContent.js
> Add user guide to user home page

- frontend/src/components/BaseWorkspaceList.js
- frontend/src/components/FocusOverlay.js
- frontend/src/components/InfoBox.js
- frontend/src/components/ProjectNavBar.js
- frontend/src/static/userGuide.json
- frontend/src/static/userGuide.schema.json
- frontend/src/views/home/UserViewContent.js
- frontend/src/views/manager/CourseEditor.js
- frontend/src/views/manager/CourseList.js
- frontend/src/views/mapper/Course.js
- frontend/src/views/mapper/PrerequisiteContainer.js
- frontend/src/views/project/MergeList.js
- frontend/src/views/project/ProjectView.js
- frontend/src/views/project/UserWorkspaceList.js
~~Depends on #333 (change base to master after merging)~~ done
Fixes #328
> Add staff-only parts to user guide

- frontend/src/views/login/LoginView.js
- frontend/src/views/project/CloneView.js
This brings back the flashing :(
But the button stays disabled :)
> Show existing workspace in join clone view

- rekisteriseloste.md
Part of #353 
[Rendered](https://github.com/rage/concepts/blob/rekisteriseloste/rekisteriseloste.md)
> Add privacy policy

- Dockerfile
- backend/schema/extra.graphql
- backend/schema/generated/schema.graphql
- backend/src/resolvers/Query/Authentication.js
- backend/src/saml/serviceProvider.js
- development.yml
- frontend/public/index.html
- frontend/public/res/googleInit.js
- frontend/src/graphql/Query/Authentication.js
- frontend/src/lib/authentication/google.js
- frontend/src/lib/authentication/haka.js
- frontend/src/lib/authentication/index.js
- frontend/src/lib/eventMiddleware.js
- frontend/src/views/login/LoginView.js
- frontend/src/views/user/UserView.js
- production.yml
A build-time frontend env var is pretty hacky
> Make Haka login URL dynamic

- backend/schema/datamodel.prisma
- backend/schema/extra.graphql
- backend/schema/generated/prisma-client/index.d.ts
- backend/schema/generated/prisma-client/prisma-schema.js
- backend/schema/generated/prisma-client/prisma.graphql
- backend/schema/generated/schema.graphql
- backend/src/resolvers/Mutation/Concept.js
- backend/src/resolvers/Mutation/Course.js
- backend/src/resolvers/Mutation/Workspace.js
- docker-compose.yml
- frontend/package.json
- frontend/src/apollo/update/course.js
- frontend/src/apollo/update/index.js
- frontend/src/apollo/update/workspace.js
- frontend/src/graphql/Mutation/Course.js
- frontend/src/graphql/Mutation/Workspace.js
- frontend/src/graphql/Query/Course.js
- frontend/src/graphql/Query/Workspace.js
- frontend/src/lib/arrayShift.js
- frontend/src/lib/sortableMoc.js
- frontend/src/views/manager/ConceptEditor.js
- frontend/src/views/manager/ConceptList.js
- frontend/src/views/manager/ConceptListItem.js
- frontend/src/views/manager/CourseList.js
- frontend/src/views/manager/WorkspaceManagementView.js
- frontend/src/views/manager/editorStyles.js
- frontend/yarn.lock
> Manual ordering in manager

- frontend/src/graphql/Mutation/CourseLink.js
- frontend/src/views/manager/ConceptList.js
- frontend/src/views/manager/CourseList.js
- frontend/src/views/manager/ordering.js
- frontend/src/views/mapper/ActiveCourse.js
- frontend/src/views/mapper/Course.js
- frontend/src/views/mapper/CourseContainer.js
- frontend/src/views/mapper/CourseTray.js
- frontend/src/views/mapper/PrerequisiteContainer.js
> Order courses and concepts in mapper view

- frontend/package.json
- frontend/src/index.js
- frontend/yarn.lock
> Add sentry error monitoring

- frontend/src/App.js
- frontend/src/components/NavBar.js
- frontend/src/components/WorkspaceNavBar.js
- frontend/src/views/manager/WorkspaceManagementView.js
> Store manager view open course in url

- backend/schema/extra.graphql
- backend/schema/generated/schema.graphql
- backend/src/resolvers/Mutation/ConceptLink.js
- frontend/src/graphql/Fragment/ConceptLink.js
- frontend/src/views/heatmap/HeatmapView.js
Add subscriptions to heat-map.
> Heatmap subscription

- frontend/src/views/heatmap/HeatmapView.js
- frontend/src/views/manager/ConceptListItem.js
- frontend/src/views/mapper/concept/Concept.js
> Remove tooltip animations

- frontend/src/views/graph/CytoGraphView.js
> Notify when no links exist in graph view

- frontend/src/views/graph/CytoGraphView.js
> Show name of concept in graph popper

- frontend/src/views/heatmap/HeatmapView.js
> Add number of concepts to heatmap cells

- frontend/src/apollo/update/conceptLink.js
- frontend/src/apollo/useUpdatingSubscription.js
- frontend/src/graphql/Fragment/Workspace.js
- frontend/src/views/graph/CytoGraphView.js
- frontend/src/views/heatmap/HeatmapView.js
Add subscriptions to graph view.
Part of: #411
> Graph subscriptions

- frontend/src/components/WorkspaceNavBar.js
- frontend/src/views/project/MergeList.js
- frontend/src/views/project/ProjectView.js
- frontend/src/views/project/UserWorkspaceList.js
> Help tooltips for disabled buttons in project view

- frontend/src/components/ConceptTooltipContent.js
- frontend/src/dialogs/tagSelectUtils.js
- frontend/src/graphql/Fragment/Workspace.js
- frontend/src/views/graph/CytoGraphView.js
- frontend/src/views/manager/ConceptListItem.js
- frontend/src/views/mapper/concept/Concept.js
> Tags in poppers

- backend/schema/datamodel.prisma
- backend/schema/extra.graphql
- backend/schema/generated/schema.graphql
- backend/src/resolvers/Mutation/Sharing.js
- backend/src/resolvers/Query/Workspace.js
> Make most graphql return values required

- backend/src/resolvers/Mutation/CourseLink.js
- backend/src/resolvers/Subscription/Concept.js
- backend/src/resolvers/Subscription/ConceptLink.js
- backend/src/resolvers/Subscription/Course.js
- backend/src/resolvers/Subscription/CourseLink.js
- backend/src/resolvers/Subscription/Member.js
- backend/src/resolvers/Subscription/ProjectWorkspace.js
- backend/src/resolvers/Subscription/Workspace.js
- backend/src/util/accessControl.js
Check if the user for a specific subscription is allowed to view the resource before publishing.
> Subscription permissions

- frontend/src/components/EditableTable.js
- frontend/src/views/project/PointGroupsView.js
* Added tooltips to export and "new group" button.
* Changed export button to icon.
> Point groups improvement

- frontend/src/components/ProjectNavBar.js
- frontend/src/views/project/PointGroupsView.js
> Add some tooltips to point groups view

- frontend/src/views/home/UserViewContent.js
> Add tooltip for userviewcontent

- backend/src/resolvers/Subscription/Concept.js
- backend/src/resolvers/Subscription/ConceptLink.js
- backend/src/resolvers/Subscription/Course.js
- backend/src/resolvers/Subscription/CourseLink.js
- backend/src/resolvers/Subscription/Member.js
- backend/src/resolvers/Subscription/Objective.js
- backend/src/resolvers/Subscription/ProjectWorkspace.js
- backend/src/resolvers/Subscription/Workspace.js
- backend/src/resolvers/Subscription/subscriptionUtil.js
> Make subscription resolvers generic

- backend/src/resolvers/Query/Workspace.js
This has already been deployed into production since it's :fire:
> Fix check in workspaceBySourceTemplate

- backend/src/resolvers/Type/Course.js
> Minor fixes

- frontend/src/views/coursemapper/ActiveCourse.js
- frontend/src/views/coursemapper/Course.js
> Set course mapper to use objectives instead of concepts

- frontend/src/views/conceptmapper/ConceptMapperView.js
- frontend/src/views/conceptmapper/ConceptNode.js
> Distinguish objectives from concepts in concept mapper

- backend/src/resolvers/Mutation/Concept.js
- frontend/src/lib/useCachedMutation.js
- frontend/src/views/conceptmapper/ConceptMapperView.js
- frontend/src/views/conceptmapper/ConceptNode.js
- frontend/src/views/conceptmapper/CourseList.js
> Concept mapper toolbar

- frontend/src/dialogs/concept/useCreateConceptDialog.js
- frontend/src/views/conceptmapper/ConceptMapperView.js
- frontend/src/views/conceptmapper/ConceptNode.js
- frontend/src/views/coursemapper/ActiveCourse.js
- frontend/src/views/coursemapper/Course.js
> Concept mapper background context

- frontend/src/views/conceptmapper/ConceptMapperView.js
- frontend/src/views/conceptmapper/ConceptNode.js
> Dropdown button

- frontend/src/views/conceptmapper/ConceptMapperView.js
> Confirm before deleting concepts in concept mapper

- frontend/src/views/conceptmapper/ConceptMapperView.js
> Store absolute zoom origin instead of viewport-relative position

- backend/src/resolvers/Mutation/BaseLink.js
- frontend/src/apollo/update/member.js
- frontend/src/components/EditableTable.js
- frontend/src/dialogs/intro/IntroDialog.js
- frontend/src/graphql/Mutation/Concept.js
- frontend/src/lib/store/login.js
- frontend/src/views/conceptmapper/ConceptMapperView.js
- frontend/src/views/conceptmapper/CourseList.js
- frontend/src/views/conceptmapper/HackySlider.js
- frontend/src/views/coursemapper/ActiveCourse.js
- frontend/src/views/coursemapper/Course.js
- frontend/src/views/graph/GraphView.js
- frontend/src/views/manager/editorStyles.js
- frontend/src/views/user/UserView.js
Normal eslint fixes, should be merged after #498
> Fix eslint problems

- backend/schema/generated/schema.graphql
- backend/schema/source/extra.prisma
- backend/src/resolvers/Mutation/Admin.js
Fixes #319
* Guest deactivation moved to Prisma instead of calculating locally
* Added deleting workspaces with no participants
Merge after #499
> Improve cleanup mutation

- backend/schema/generated/schema.graphql
- frontend/src/views/manager/ConceptList.js
- frontend/src/views/manager/CourseList.js
> Add message when concept/course list has no items

- frontend/src/components/WorkspaceNavBar.js
> Hide members

- backend/src/resolvers/Mutation/Concept.js
> Fix creating common concepts

- backend/src/static/port.schema.json
Fix porting by adding missing fields.
> Fix porting

- frontend/src/components/WorkspaceNavBar.js
Set share link visible only for owners
> Share link

- backend/src/resolvers/Mutation/Import.js
> Goaltags backend

- backend/src/controllers/exportAPI.js
- backend/src/resolvers/Mutation/Import.js
- backend/src/static/port.schema.json
Add positions of concepts to importing and exporting.
> Positions to export and import

- frontend/src/views/conceptmapper/ConceptMapperView.js
- frontend/src/views/conceptmapper/CourseList.js
> Concept mapper zoom fix

- backend/schema/generated/prisma-client/index.d.ts
- backend/schema/generated/prisma-client/prisma-schema.js
- backend/schema/generated/prisma-client/prisma.graphql
- backend/schema/generated/schema.graphql
- backend/schema/source/datamodel.prisma
- backend/schema/source/extra.prisma
- backend/src/resolvers/Mutation/BaseLink.js
- backend/src/resolvers/Mutation/Concept.js
- backend/src/resolvers/Mutation/GoalLink.js
- frontend/src/graphql/Fragment/Concept.js
- frontend/src/graphql/Fragment/ConceptLink.js
- frontend/src/graphql/Fragment/CourseLink.js
- frontend/src/graphql/Mutation/ConceptLink.js
- frontend/src/graphql/Mutation/CourseLink.js
- frontend/src/graphql/Query/Course.js
- frontend/src/views/conceptmapper/ConceptMapperView.js
- frontend/src/views/coursemapper/CourseContainer.js
- frontend/src/views/coursemapper/MapperLinks.js
- frontend/src/views/coursemapper/concept/ConceptLink.js
> Link weight UI

- frontend/src/views/project/UserWorkspaceList.js
> Add button to clone project template directly

- backend/schema/generated/schema.graphql
- backend/schema/source/extra.prisma
- backend/src/resolvers/Mutation/Project.js
- frontend/src/components/BaseWorkspaceList.js
- frontend/src/graphql/Mutation/Project.js
- frontend/src/views/project/MergeList.js
> Add option to promote merged workspace to a template

- backend/src/resolvers/Mutation/Workspace.js
> Fix bug in cloning workspaces with common concepts

- frontend/package.json
- frontend/src/views/conceptmapper/ConceptMapperView.js
- frontend/yarn.lock
Fixes #547 
~~Depends on #552~~
> Concept mapper layout

- compose.ps1
- prisma.ps1
Add scripts to support development in windows.
> Windows support

- backend/src/controllers/exportAPI.js
- backend/src/resolvers/Mutation/Import.js
Other things to do:
Probably fixes #535 after that tag thing is fixed
> Fix things in import/export

- frontend/src/views/conceptmapper/ConceptNode.js
> Add tooltip for concept mapper nodes

- frontend/src/views/goals/GoalView.js
Fix cache updates temporarily in goal view
> Temporal fix

- frontend/src/views/graph/GraphView.js
- frontend/src/views/graph/tarjan.js
Fixes #514 
Might be slightly inefficient
> Improve graph layout and add cycle detection

- frontend/src/views/graph/GraphView.js
> Show cycle count at top of graph view

- frontend/src/components/BaseWorkspaceList.js
- frontend/src/views/project/UserWorkspaceList.js
> Delete menu option for cloned workspaces

- backend/src/resolvers/Type/Workspace.js
- frontend/src/components/BaseWorkspaceList.js
- frontend/src/graphql/Mutation/Workspace.js
- frontend/src/graphql/Query/Project.js
- frontend/src/views/project/ProjectView.js
- frontend/src/views/project/UserWorkspaceList.js
> Improve user workspace list

- frontend/src/views/graph/GraphView.js
~~TODO: zoom into box when clicking cycle warning~~
> Add boxes around cycles in graph view

- backend/src/controllers/exportAPI.js
- backend/src/util/ordering.js
- frontend/src/views/coursemapper/ActiveCourse.js
- frontend/src/views/coursemapper/Course.js
- frontend/src/views/manager/ConceptList.js
- frontend/src/views/manager/CourseList.js
> Course menu order

- backend/schema/generated/prisma-client/index.d.ts
- backend/schema/generated/prisma-client/prisma-schema.js
- backend/schema/generated/prisma-client/prisma.graphql
- backend/schema/generated/schema.graphql
- backend/schema/source/datamodel.prisma
- backend/schema/source/extra.prisma
- backend/src/resolvers/Mutation/Course.js
- frontend/src/graphql/Fragment/Course.js
- frontend/src/graphql/Fragment/CourseLink.js
- frontend/src/graphql/Mutation/Course.js
- frontend/src/graphql/Query/Workspace.js
- frontend/src/views/manager/ConceptList.js
- frontend/src/views/manager/CourseEditor.js
- frontend/src/views/manager/CourseList.js
- frontend/src/views/manager/search.js
> Add description and filtering for courses

- frontend/src/components/DividerWithText.js
- frontend/src/views/coursemapper/CourseMapperView.js
- frontend/src/views/goals/Courses.js
- frontend/src/views/goals/GoalView.js
- frontend/src/views/goals/Goals.js
- frontend/src/views/goals/styles.js
- frontend/src/views/manager/ConceptEditor.js
- frontend/src/views/manager/CourseEditor.js
> Cut off lines to prevent overlap with headers/forms

- backend/src/util/ordering.js
- frontend/src/dialogs/course/useCreateCourseDialog.js
- frontend/src/graphql/Fragment/Course.js
- frontend/src/graphql/Query/Workspace.js
- frontend/src/views/coursemapper/CourseTray.js
- frontend/src/views/manager/CourseList.js
> Add topological sorting for courses

- frontend/src/components/ConceptTooltipContent.js
- frontend/src/views/manager/CourseListItem.js
> Add tooltip for courses in manager view

- backend/src/controllers/loginAPI.js
> Add staff permissions when creating faculty/staff user from Haka login

- backend/schema/generated/schema.graphql
- backend/schema/source/extra.prisma
- backend/src/resolvers/Mutation/Project.js
- frontend/src/components/ProjectNavBar.js
- frontend/src/dialogs/alert/Alert.js
- frontend/src/dialogs/alert/index.js
- frontend/src/graphql/Mutation/Project.js
- frontend/src/views/home/ProjectList.js
> Add option to delete workspaces when deleting project

- frontend/src/dialogs/concept/useCreateConceptDialog.js
- frontend/src/dialogs/concept/useEditConceptDialog.js
- frontend/src/dialogs/course/useCreateCourseDialog.js
- frontend/src/dialogs/course/useEditCourseDialog.js
- frontend/src/graphql/Query/Course.js
- frontend/src/views/coursemapper/Course.js
> Show course description in course mapper

- frontend/src/views/manager/ConceptList.js
- frontend/src/views/manager/CourseList.js
- frontend/src/views/manager/search.js
> Add buttons to filter by tag in manager view

- backend/schema/generated/prisma-client/index.d.ts
- backend/schema/generated/prisma-client/prisma-schema.js
- backend/schema/generated/prisma-client/prisma.graphql
- backend/schema/generated/schema.graphql
- backend/schema/source/datamodel.prisma
- backend/src/controllers/exportAPI.js
- backend/src/resolvers/Mutation/Import.js
- backend/src/static/port.schema.json
> add course description to import/export

- backend/schema/generated/schema.graphql
- backend/schema/source/extra.prisma
- backend/src/controllers/exportAPI.js
- backend/src/index.js
- backend/src/resolvers/Mutation/Authentication.js
- backend/src/util/restAuth.js
- frontend/src/components/BaseWorkspaceList.js
- frontend/src/components/WorkspaceNavBar.js
> Markdown export

- frontend/src/views/conceptmapper/ConceptMapperView.js
- frontend/src/views/conceptmapper/ConceptNode.js
fixes: #602 
Highlight concepts and objectives that have more links.
> Concept importance

- frontend/src/views/graph/GraphView.js
> Search concepts in graph view
